class AfricaCountries {
  static final Map<String, String> data = {
    "AF-DZ": "Algeria",
    "AF-AO": "Angola",
    "AF-BJ": "Benin",
    "AF-BW": "Botswana",
    "AF-BF": "Burkina Faso",
    "AF-BI": "Burundi",
    "AF-CV": "Cabo Verde",
    "AF-CM": "Cameroon",
    "AF-CF": "Central African Republic",
    "AF-TD": "Chad",
    "AF-KM": "Comoros",
    "AF-CG": "Republic of the Congo",
    "AF-CD": "Democratic Republic of the Congo",
    "AF-CI": "Côte d'Ivoire",
    "AF-DJ": "Djibouti",
    "AF-EG": "Egypt",
    "AF-GQ": "Equatorial Guinea",
    "AF-ER": "Eritrea",
    "AF-SZ": "Eswatini",
    "AF-ET": "Ethiopia",
    "AF-GA": "Gabon",
    "AF-GM": "Gambia",
    "AF-GH": "Ghana",
    "AF-GN": "Guinea",
    "AF-GW": "Guinea-Bissau",
    "AF-KE": "Kenya",
    "AF-LS": "Lesotho",
    "AF-LR": "Liberia",
    "AF-LY": "Libya",
    "AF-MG": "Madagascar",
    "AF-MW": "Malawi",
    "AF-ML": "Mali",
    "AF-MR": "Mauritania",
    "AF-MU": "Mauritius",
    "AF-MA": "Morocco",
    "AF-MZ": "Mozambique",
    "AF-NA": "Namibia",
    "AF-NE": "Niger",
    "AF-NG": "Nigeria",
    "AF-RW": "Rwanda",
    "AF-ST": "Sao Tome and Principe",
    "AF-SN": "Senegal",
    "AF-SC": "Seychelles",
    "AF-SL": "Sierra Leone",
    "AF-SO": "Somalia",
    "AF-ZA": "South Africa",
    "AF-SS": "South Sudan",
    "AF-SD": "Sudan",
    "AF-TZ": "Tanzania",
    "AF-TG": "Togo",
    "AF-TN": "Tunisia",
    "AF-UG": "Uganda",
    "AF-ZM": "Zambia",
    "AF-ZW": "Zimbabwe",
  };
}
